language: go
go:
  - "1.10"
install:
  - go get github.com/magefile/mage
  - go get -d github.com/gohugoio/hugo
  - cd ${GOPATH:-$HOME/go}/src/github.com/gohugoio/hugo
  - mage vendor
  - mage install
script: cd liron-li/cheaptalks.org && hugo
notifications:
  email:
    - liron.li@outlook.com
